### PR TITLE
163204 Updated Solution Template Blades & Altered the Default LANSA MSI Depe…

### PR DESCRIPTION
**Pull request by ashutosh-kumar1**
…nding on LANSA Version

# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

* Updated the solution blades as per the provided comments
* Altered the MSI URL as per the lansa version provided

### CODE REVIEW

**Review by robe070 — COMMENTED** [review]
`databaseLogin`  
   "toolTip": "The admin user of the Database",

`databaseLoginPassword` is not under our control, so it must not be constrained.
   "toolTip": "The password of the admin user of the Database",

`minimumInstanceCount` & `maximumInstanceCount`
   "validationMessage": "Only numerals **_are are_** allowed. The value must be from 1-100."

`webServerMaxConnect`
   Numeric field

`maxSizeBytes`
   Numeric field

**Comment by ashutosh-kumar1** [comment]
@robe070, Review comments incorporated. The webServerMaxConnect and maxSizeBytes variables have been changed to integer values though they were defaulted to and accepted as string values in the existing template.

**Review by robe070 — APPROVED** [review]
Changes are correct.

**Comment by robe070** [comment]
I've noticed a few more cases to provide automatic validation.
Edition | Valid RSON
-- | --
Basic | Basic
Standard | Sx
Premium | Px


Application Gateway SKU Tier | Valid Application Gateway SKU Name
-- | --
Standard | Standard x
WAF | WAF x

**Comment by ashutosh-kumar1** [comment]
@robe070, Do the changes need to be made for default values for the provided fields? I can see them the same way in mainTemplate.json. I also tried deploying it with the existing values and it worked. Please confirm.

**Comment by robe070** [comment]
> Do the changes need to be made for default values for the provided fields? I can see them the same way in mainTemplate.json. I also tried deploying it with the existing values and it worked. Please confirm.

Which fields? Existing values in `createUIDefinition.json`?

**Comment by ashutosh-kumar1** [comment]
Sorry for bothering you @robe070. Took some time to understand your comment. Have taken care of the requirements and pushed the required changes.

**Pull request merged**
