### PR TITLE
fixed dependsOn error

### PR DESCRIPTION
**Pull request by ganeshk146**

### CODE REVIEW

**Comment by robe070** [comment]
I've disabled the template-CI Clone PR trigger.

I'm going to run Templates-CI to double check only expected errors are there.

Then I will disable the ARM-TTK tests until they are fixed and re-run the CI pipeline

**Comment by robe070** [comment]
I see you have modified the Template-CI pipeline. Whats that meant to achieve?

**Comment by robe070** [comment]
...and I see you've disabled many of the tasks.

So, can you run Templates-CI to double check only expected errors are there.

Then disable just the ARM-TTK tests (until they are fixed) and re-run the CI pipeline

**Comment by ganeshk146** [comment]
> I see you have modified the Template-CI pipeline. Whats that meant to achieve?



> ...and I see you've disabled many of the tasks.
> 
> So, can you run Templates-CI to double check only expected errors are there.
> 
> Then disable just the ARM-TTK tests (until they are fixed) and re-run the CI pipeline

I reverted all the changes I made when I was fixing the errors in the pipeline

**Comment by robe070** [comment]
I must have seen it before you reverted it.

I've just merged the changes and I'm running the pipeline.

**Comment by robe070** [comment]
I've checked that only expected errors in pipeline.

I've now disabled the ARM-TTK tests (until they are fixed) and re-running the CI pipeline

**Pull request merged**
