### PR TITLE
Added latest api versions

### PR DESCRIPTION
**Pull request by VarunChopraAccolite**
# PR Checklist

Check these items before submitting a PR... 

[Contribution Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/README.md)

[Best Practice Guide](https://github.com/Azure/azure-quickstart-templates/blob/master/1-CONTRIBUTION-GUIDE/best-practices.md)

- [ ] - Please check this box once you've submitted the PR if you've read through the Contribution Guide and best practices checklist.

## Changelog

*
*
*

### CODE REVIEW

**Comment by robe070** [comment]
Unless there is an urgent need, with a good reason, I won't be merging this PR until it passes the tests, which it probably will do given the simplicity of the changes and that the only reason for the failure was that the validation was cancelled by Varun.
@VarunChopraAccolite Maybe restart the check? Or does it require the PR to be updated?

**Comment by knagasekharreddy** [comment]
I followed issue #30 steps and i noticed same error which we have in issue after that i modified and execute the azuredeploy.json file.

When i ran this command `((Get-AzResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes | Where-OBject ResourceTypeName -eq publicIPAddresses).apiversions`

I noticed below apiversions and i added latest apiversions in azuredeploy.json file where we are getting errors and i fix it sucessfully.


`PS C:\WINDOWS\system32> ((Get-AzResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes | Where-OBject ResourceTypeName -eq publicIPAddresses).apiversions`
2019-12-01
2019-11-01
2019-09-01
2019-08-01
2019-07-01
2019-06-01
2019-04-01
2019-02-01
2018-12-01
2018-11-01
2018-10-01
......................

@robe070 @VarunChopraAccolite let me know if any thing else required..?

**Comment by knagasekharreddy** [comment]
I followed issue 30 steps and i noticed same error which we have in issue after that i modified and execute the azuredeploy.json file.

When i ran this command `((Get-AzResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes | Where-OBject ResourceTypeName -eq publicIPAddresses).apiversions`

I noticed below apiversions and i added latest apiversions in azuredeploy.json file where we are getting errors and i fix it sucessfully.

`PS C:\WINDOWS\system32> ((Get-AzResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes | Where-OBject ResourceTypeName -eq publicIPAddresses).apiversions`
2019-12-01
2019-11-01
2019-09-01
2019-08-01
2019-07-01
2019-06-01
2019-04-01
2019-02-01
2018-12-01
2018-11-01
2018-10-01
..........

@robe070 @VarunChopraAccolite let me know if any thing else required..?

**Comment by VarunChopraAccolite** [comment]
> Unless there is an urgent need, with a good reason, I won't be merging this PR until it passes the tests, which it probably will do given the simplicity of the changes and that the only reason for the failure was that the validation was cancelled by Varun.
> @VarunChopraAccolite Maybe restart the check? Or does it require the PR to be updated?

@robe070 sure, I had rerun the tests. It's passing the TTK tests. I will verify running the template and keep you posted. It seems that the inline API version is not supporting EastUS location. It need rework.
image

```
##[error]At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.
##[error]Details:
##[error]NoRegisteredProviderFound: No registered resource provider found for location 'eastus' and API version '2019-12-01-preview' for type 'servers'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-04-01-preview, 2015-05-01-preview, 2017-03-01-preview, 2017-10-01-preview, 2018-06-01-preview, 2019-06-01-preview, 2020-02-02-preview'. The supported locations are 'australiacentral, australiaeast, australiasoutheast, brazilsouth, canadacentral, canadaeast, centralindia, centralus, eastasia, eastus, eastus2, francecentral, germanywestcentral, japaneast, japanwest, koreacentral, koreasouth, northcentralus, northeurope, norwayeast, southafricanorth, southcentralus, southindia, southeastasia, switzerlandnorth, uaenorth, uksouth, ukwest, westcentralus, westeurope, westindia, westus, westus2'.
##[error]Check out the troubleshooting guide to see if your issue is addressed: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops#troubleshooting
##[error]Task failed while creating or updating the template deployment.
```

**Comment by VarunChopraAccolite** [comment]
hi @robe070 
I request you to resume the review process in another PR, it had passed the TTK along with the Deployment. I had fixed the resource deployment of the template. Thanks for understanding.

https://github.com/lansa/azure-quickstart-templates/pull/4

**Comment by robe070** [comment]
@knagasekharreddy 
> `PS C:\WINDOWS\system32> ((Get-AzResourceProvider -ProviderNamespace Microsoft.Network).ResourceTypes | Where-OBject ResourceTypeName -eq publicIPAddresses).apiversions`
> 2019-12-01

This is the first problem, the Provider of the resource is `Microsoft.Sql`. And the type is `servers`

> I noticed below apiversions and i added latest apiversions in azuredeploy.json file where we are getting errors and i fix it sucessfully.

This is the second problem, the ARM TTK is only checking the date is less than 2 years. It is not validating that it is correct for the resource. It presumes you've deployed the template successfully.

Which leads to the third problem, if you deployed the template you did not choose `new` database. So the resource you changed was not used because its conditioned on `new` database. The pipeline uses `new` database so it found the error. Its not just in `US East` that this error occurs.

And now I've noticed where you originally obtained `2014-04-01` - the VS Code tool tips. These are out of date. The same list as the ARM TTK test provides. Or maybe you obtained them from there - which you were told not to. Never use them. Always use the cmdlet. Always use the latest the cmdlet lists.

**Comment by robe070** [comment]
This has been useful in identifying the pitfalls in using the correct API Version. I've written a Wiki page to cover this. Please review that it would instruct you clearly to avoid the pitfalls:

https://github.com/robe070/cookbooks/wiki/How-to-obtain-valid-API-Version

**Pull request closed without merging**
